#!/usr/bin/env bash

# Actual script directory path
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

# Process ID
PID=`ps -aux | grep -e "[j]oin_captcha_bot.py" | awk 'FNR == 1 {print $2}'`

if [ -z "$PID" ]; then
    echo "Script is not running."
    exit 1
fi

echo "Killing script, please wait..."
kill $PID
while $(kill -0 $PID 2>/dev/null); do
    sleep 1
done
$DIR/status

exit 0
