#!/bin/bash

PID=`ps -aux | grep -e "[j]oin_captcha_bot.py" | awk 'FNR == 1 {print $2}'`

if [ ! -z "$PID" ]; then
    kill $PID
    echo "Killing script..."
    sleep 10
    ./status
    exit 0
else
    echo "Script is not running."
    exit 1
fi
