#!/usr/bin/env bash

PID=`ps -aux | grep -e "[j]oin_captcha_bot.py" | awk 'FNR == 1 {print $2}'`

if [ -z "$PID" ]; then
    echo "Script is not running."
    exit 1
fi

kill $PID
echo "Killing script, please wait..."
while $(kill -9 $PID 2>/dev/null); do
    sleep 1
done
./status

exit 0
