#!/usr/bin/env bash

# Actual script directory path
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

cd $DIR
rm -f $DIR/*.json

wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/ar.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/be.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/ca.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/de.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/el.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/en.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/eo.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/es.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/eu.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/fa.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/fr.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/gl.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/id.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/it.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/kn.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/ko.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/nl.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/pl.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/pt_br.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/ru.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/sk.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/tr.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/uk.json
wget https://raw.githubusercontent.com/J-Rios/TLG_JoinCaptchaBot/master/sources/language/zh_cn.json

exit 0
