#!/usr/bin/env bash

# Actual script directory path
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

CHAT="${1}"

echo ""
cat $DIR/../src/data/chats/$CHAT/configs.json
echo ""

exit 0
