#!/usr/bin/env bash

# Actual script directory path
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

# Continuous check and show users joins and captcha process
tail -n1000 -f $DIR/../output.log | grep -e "New join detected:" -e "Captcha not solved, kicking" -e "Captcha solved by"

exit 0
